### ISSUE TITLE
Unable to install on Symfony 3.3

### ISSUE THREAD

**Issue by BenoitDuffez** [fre5h/DoctrineEnumBundle#99]
First, thank you for your work.

Then, I'm not sure it's related to your bundle, but I am new to Symfony and I am sorry if my issue is off topic.

I have followed the instructions on the readme, however it doesn't seem to work.  
Here's the error:

```
$ php bin/console
PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'Unable to resolve service "AppBundle\DBAL\Types\QuoteStateType": its constructor must be public.' in /path/to/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:126
Stack trace:
#0 /path/to/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(136): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->getConstructor(Object(Symfony\Component\DependencyInjection\Definition), false)
#1 /path/to/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(102): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#2 /path/to/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(57): Symfony\ in /path/to/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php on line 126
```

Now I don't understand why composer/Symfony believes this should be a service.  
Here's what I have implemented (git output shortened to file names only for clarity, no other file was modified):

```
$ git status
Changes not staged for commit:
	modified:   app/AppKernel.php
	modified:   app/config/config.yml
	modified:   composer.json
	modified:   composer.lock
	modified:   src/AppBundle/Entity/Quote.php

Untracked files:
	src/AppBundle/DBAL/
```

Here are the actual changes (except for `composer.lock`):

```diff
$ git diff app/ src/ composer.json
diff --git a/app/AppKernel.php b/app/AppKernel.php
index 0f94f53..4488b99 100644
--- a/app/AppKernel.php
+++ b/app/AppKernel.php
@@ -17,6 +17,7 @@ class AppKernel extends Kernel
             new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
             new AppBundle\AppBundle(),
             new Knp\Bundle\SnappyBundle\KnpSnappyBundle(),
+            new Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle(),
         ];
 
         if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
diff --git a/app/config/config.yml b/app/config/config.yml
index aacabf3..b3e99f8 100644
--- a/app/config/config.yml
+++ b/app/config/config.yml
@@ -48,6 +48,8 @@ doctrine:
         user: '%database_user%'
         password: '%database_password%'
         charset: UTF8
+        types:
+            QuoteStateType: AppBundle\DBAL\Types\QuoteStateType
         # if using pdo_sqlite as your database driver:
         #   1. add the path in parameters.yml
         #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
diff --git a/composer.json b/composer.json
index fe281db..b26b444 100644
--- a/composer.json
+++ b/composer.json
@@ -24,6 +24,7 @@
         "aptoma/twig-markdown": "^2.0",
         "doctrine/doctrine-bundle": "^1.6",
         "doctrine/orm": "^2.5",
+        "fresh/doctrine-enum-bundle": "~5.0",
         "h4cc/wkhtmltopdf-amd64": "^0.12.3",
         "incenteev/composer-parameter-handler": "^2.0",
         "kbsali/redmine-api": "~1.0",
diff --git a/src/AppBundle/Entity/Quote.php b/src/AppBundle/Entity/Quote.php
index bed0057..cdd750b 100644
--- a/src/AppBundle/Entity/Quote.php
+++ b/src/AppBundle/Entity/Quote.php
@@ -6,6 +6,8 @@ use Doctrine\Common\Collections\ArrayCollection;
 use Doctrine\ORM\Mapping as ORM;
 use Redmine\Client;
 use Symfony\Component\Validator\Constraints as Assert;
+use AppBundle\DBAL\Types\QuoteStateType;
+use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert;
 
 /**
  * Quote
@@ -102,6 +104,14 @@ class Quote
         */
        private $invoices;
 
+    /**
+     * @var string
+     *
+     * @ORM\Column(name="state", type="QuoteStateType")
+     * @DoctrineAssert\Enum(entity="AppBundle\DBAL\Types\QuoteStateType")
+     */
+    private $state;
+
        public function __construct() {
                $this->sections = new ArrayCollection();
                $this->invoices = new ArrayCollection();
```

Here's my enum class:

```php
$ cat src/AppBundle/DBAL/Types/QuoteStateType.php 
<?php

namespace AppBundle\DBAL\Types;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class QuoteStateType extends AbstractEnumType {
    const DRAFT = 'draft';
    const REJECTED = 'rejected';
    const REPLACED = 'replaced';
    const ACCEPTED = 'accepted';

    // Need to change?
    // => https://github.com/fre5h/DoctrineEnumBundle#hook-for-doctrine-migrations

    protected static $choices = [
        self::DRAFT       => 'Draft',
        self::REJECTED    => 'Rejected',
        self::REPLACED    => 'Replaced',
        self::ACCEPTED    => 'Accepted',
    ];
}
```

Did I do something wrong?  
Debian 8, php5.6, Symfony 3.3.0

**Comment by fre5h** [comment]
@BenoitDuffez I tried to investigate quickly, but didn't resolve the issue, need more time.
But two things I found.
First, try to update to Symfony 3.3.2.
Second, add the following parameter for you doctrine config.

```yaml
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%" # <-- This one, and set the version of your database
        # other configs...
```

I am not sure if it helps, but very often people miss this option

**Comment by BenoitDuffez** [comment]
Thanks for the quick feedback.
Not sure exactly what version you are expecting, I'm guessing MySQL's.

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
```

Here's how it looks like in `app/config/parameters.yml` (only the last line was added):

```
# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: XYZ
    database_user: ABCD
    database_server_version: 5.7
```
and:
```diff
$ git diff app/config/config.yml
diff --git a/app/config/config.yml b/app/config/config.yml
index aacabf3..13f337b 100644
--- a/app/config/config.yml
+++ b/app/config/config.yml
@@ -47,7 +47,10 @@ doctrine:
         dbname: '%database_name%'
         user: '%database_user%'
         password: '%database_password%'
+        server_version: '%database_server_version%'
         charset: UTF8
+        types:
+            QuoteStateType: AppBundle\DBAL\Types\QuoteStateType
         # if using pdo_sqlite as your database driver:
         #   1. add the path in parameters.yml
         #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
```

Did not solve. I will try with the latest Symfony.

**Comment by BenoitDuffez** [comment]
It works! It must be a Symfony 3.0.0 bug.
Thanks for the support!
